import time
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
#img = cv.imread('simple.jpeg',0)
img = cv.imread('1520530334850094714.png',0)

start = time.time()
orb = cv.ORB_create(nfeatures=1225, nlevels=3)
#orb = cv.ORB_create(nlevels=1)
kp1 = orb.detect(img,None)
kp1, des1 = orb.compute(img, kp1)
end = time.time()
img21 = cv.drawKeypoints(img, kp1, None, color=(0,255,0), flags=0)
#plt.imshow((img21), plt.show(block=False))
print("ORB Time:")
print(end - start)
print("ORB key points:")
print(len(kp1))
print(kp1[0])
print("ORB descriptors:")
print(len(des1))
print(des1)
print(len(des1[0]))
print(des1[0])

start = time.time()
#akaze = cv.AKAZE_create(nfeatures=1000)
#akaze = cv.AKAZE_create(descriptor_type = cv.AKAZE.DESCRIPTOR_MLDB, descriptor_size = 256, descriptor_channels = 3, threshold = 0.001, nOctaves = 4, nOctaveLayers = 4, diffusivity = cv.AKAZE.DIFF_PM_G2) 
akaze = cv.AKAZE_create(descriptor_type = cv.AKAZE_DESCRIPTOR_MLDB, descriptor_size = 256, descriptor_channels = 3, threshold = 0.00001, nOctaves = 4, nOctaveLayers = 4, diffusivity = cv.KAZE_DIFF_PM_G2) 
kp2 = akaze.detect(img,None)
kp2, des2 = akaze.compute(img, kp2)
end = time.time()
img22 = cv.drawKeypoints(img, kp2, None, color=(0,255,0), flags=0)
#plt.imshow(img22), plt.show(block=False)
print("AKAZE Time:")
print(end - start)
print("AKAZE key points:")
print(len(kp2))
print(kp2[0])
print("AKAZE descriptors:")
print(len(des2))
print(des2)
print(len(des2[0]))
print(des2[0])

fig = plt.figure(figsize=(30, 10))
fig.add_subplot(1, 2,1)
plt.imshow(img21)
plt.axis('off')
plt.title("ORB")
fig.add_subplot(1, 2,2)
plt.imshow(img22)
plt.axis('off')
plt.title("AKAZE")
plt.show()
