%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "KannalaBrandt8"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 190.97847715128717
Camera1.fy: 190.9733070521226
Camera1.cx: 254.93170605935475
Camera1.cy: 256.8974428996504

# Kannala-Brandt distortion parameters
Camera1.k1: 0.0034823894022493434
Camera1.k2: 0.0007150348452162257
Camera1.k3: -0.0020532361418706202
Camera1.k4: 0.00020293673591811182
    
# Camera resolution
Camera.width: 512
Camera.height: 512

#Camera.width: 1920
#Camera.height: 1080

# Camera frames per second 
Camera.fps: 20

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000 # Tested with 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 1.0
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.05
Viewer.CameraLineWidth: 2.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -10.0
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000.0

#Viewer.KeyFrameSize: 0.05
#Viewer.KeyFrameLineWidth: 1.0
#Viewer.GraphLineWidth: 0.9
#Viewer.PointSize: 2.0
#Viewer.CameraSize: 0.08
#Viewer.CameraLineWidth: 3.0
#Viewer.ViewpointX: 0.0
#Viewer.ViewpointY: -0.7
#Viewer.ViewpointZ: -3.5
#Viewer.ViewpointF: 500.0
