// Generated by gencpp from file orb_slam3_ros_wrapper/Descriptor.msg
// DO NOT EDIT!


#ifndef ORB_SLAM3_ROS_WRAPPER_MESSAGE_DESCRIPTOR_H
#define ORB_SLAM3_ROS_WRAPPER_MESSAGE_DESCRIPTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace orb_slam3_ros_wrapper
{
template <class ContainerAllocator>
struct Descriptor_
{
  typedef Descriptor_<ContainerAllocator> Type;

  Descriptor_()
    : header()
    , rows(0)
    , cols(0)
    , type(0)
    , descdata()  {
    }
  Descriptor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rows(0)
    , cols(0)
    , type(0)
    , descdata(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _rows_type;
  _rows_type rows;

   typedef uint32_t _cols_type;
  _cols_type cols;

   typedef uint32_t _type_type;
  _type_type type;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _descdata_type;
  _descdata_type descdata;





  typedef boost::shared_ptr< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> const> ConstPtr;

}; // struct Descriptor_

typedef ::orb_slam3_ros_wrapper::Descriptor_<std::allocator<void> > Descriptor;

typedef boost::shared_ptr< ::orb_slam3_ros_wrapper::Descriptor > DescriptorPtr;
typedef boost::shared_ptr< ::orb_slam3_ros_wrapper::Descriptor const> DescriptorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator1> & lhs, const ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rows == rhs.rows &&
    lhs.cols == rhs.cols &&
    lhs.type == rhs.type &&
    lhs.descdata == rhs.descdata;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator1> & lhs, const ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace orb_slam3_ros_wrapper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1da0f4e4634ed0f924a946dd2fbf324";
  }

  static const char* value(const ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1da0f4e4634ed0fULL;
  static const uint64_t static_value2 = 0x924a946dd2fbf324ULL;
};

template<class ContainerAllocator>
struct DataType< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "orb_slam3_ros_wrapper/Descriptor";
  }

  static const char* value(const ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"Header header\n"
"\n"
"# OpenCV matrix containing the user data. A matrix of type CV_8UC1 \n"
"# with 1 row is considered to be compressed (with rtabmap::compressData() method).\n"
"# If you have one dimension unsigned 8 bits uncompressed data, make sure to transpose it\n"
"# (to have multiple rows instead of multiple columns) in order to be detected as\n"
"# not compressed.\n"
"uint32 rows\n"
"uint32 cols\n"
"uint32 type\n"
"uint8[] descdata\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rows);
      stream.next(m.cols);
      stream.next(m.type);
      stream.next(m.descdata);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Descriptor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::orb_slam3_ros_wrapper::Descriptor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rows: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.rows);
    s << indent << "cols: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cols);
    s << indent << "type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.type);
    s << indent << "descdata[]" << std::endl;
    for (size_t i = 0; i < v.descdata.size(); ++i)
    {
      s << indent << "  descdata[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.descdata[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM3_ROS_WRAPPER_MESSAGE_DESCRIPTOR_H
